name: lyarrics

services:
  lyarrics:
    image: ghcr.io/altered-tech/lyarrics:latest
    container_name: lyarrics
    environment:
      LYARRICS_MUSIC_PATH: /music
    ports:
      - "8080:8080"
    volumes:
      - lyarrics-data:/data
      - ${MUSIC_PATH}:/music

volumes:
  lyarrics-data:
